### ISSUE TITLE
Wann wird das Plugin immer hochgeladen auf den Server

### ISSUE THREAD

**Issue by LaborExperiment** [Patrick-Spiegel/0815craft-server#3]
Also wenn einer hier seinen Code hochlädt und der akzeptiert wird,
wann wird der immer übernommen also auf den Server hochgeladen?

+
Kannst du bitte den Account Putzeimer (der bin ich) vom Server entbannen, habe 5mal hintereinander den Namen Jerrycrafter05 in den Chat geschrieben, dann kam der Autoban vom Spam Plugin, tut mir auch leid musste nicht sein.

+
Wann kommst du mal wieder auf den Server?

**Comment by Patrick-Spiegel** [comment]
Ich werde noch einen CI einrichten, der das automatisch erneuert und dann Nachts den Server automatisch neustarten lassen. 

Spigot-Bans können nicht entbannt werden und du musst warten bis dieser ausläuft. 

> Wann kommst du mal wieder auf den Server?

Ich habe derzeit ein paar Probleme mit meinem Computer, ich arbeite aber an einer Lösung dafür.

**Comment by LaborExperiment** [comment]
Hallo,
kannst du bitte meine beiden Accounts Putzeimer und Kapuzenpullover entbannen, tut mir leid das ich gespammt habe (5mal hintereinander gleiche Nachricht geschrieben).
Und 1. die laufen net ab die sind permanent und 2. doch man kann die entbannen /pardon Name
